# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Game = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.Game.setGeometry(QtCore.QRect(30, 10, 741, 551))
        self.Game.setObjectName("Game")
        self.LoginPage = QtWidgets.QWidget()
        self.LoginPage.setObjectName("LoginPage")
        self.InputName = QtWidgets.QLineEdit(parent=self.LoginPage)
        self.InputName.setGeometry(QtCore.QRect(30, 40, 113, 20))
        self.InputName.setObjectName("InputName")
        self.InputPassword = QtWidgets.QLineEdit(parent=self.LoginPage)
        self.InputPassword.setGeometry(QtCore.QRect(30, 80, 113, 20))
        self.InputPassword.setObjectName("InputPassword")
        self.LoginResponse = QtWidgets.QLabel(parent=self.LoginPage)
        self.LoginResponse.setGeometry(QtCore.QRect(250, 70, 141, 21))
        self.LoginResponse.setObjectName("LoginResponse")
        self.Login = QtWidgets.QPushButton(parent=self.LoginPage)
        self.Login.setGeometry(QtCore.QRect(350, 160, 75, 24))
        self.Login.setObjectName("Login")
        self.ReadFromFile = QtWidgets.QPushButton(parent=self.LoginPage)
        self.ReadFromFile.setGeometry(QtCore.QRect(180, 160, 161, 24))
        self.ReadFromFile.setObjectName("ReadFromFile")
        self.Register = QtWidgets.QPushButton(parent=self.LoginPage)
        self.Register.setGeometry(QtCore.QRect(90, 160, 75, 24))
        self.Register.setObjectName("Register")
        self.Game.addTab(self.LoginPage, "")
        self.GamePage = QtWidgets.QWidget()
        self.GamePage.setObjectName("GamePage")
        self.mainGame = QtWidgets.QWidget(parent=self.GamePage)
        self.mainGame.setGeometry(QtCore.QRect(0, 0, 731, 521))
        self.mainGame.setObjectName("mainGame")
        self.Game.addTab(self.GamePage, "")
        self.Statistics = QtWidgets.QWidget()
        self.Statistics.setObjectName("Statistics")
        self.Game.addTab(self.Statistics, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(parent=self.menubar)
        self.menu.setObjectName("menu")
        self.menuGame = QtWidgets.QMenu(parent=self.menubar)
        self.menuGame.setObjectName("menuGame")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menuGame.menuAction())

        self.retranslateUi(MainWindow)
        self.Game.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.InputName.setText(_translate("MainWindow", "Name"))
        self.InputPassword.setText(_translate("MainWindow", "Password"))
        self.LoginResponse.setText(_translate("MainWindow", "Login Response"))
        self.Login.setText(_translate("MainWindow", "Login"))
        self.ReadFromFile.setText(_translate("MainWindow", "Read From File"))
        self.Register.setText(_translate("MainWindow", "Register"))
        self.Game.setTabText(self.Game.indexOf(self.LoginPage), _translate("MainWindow", "Tab 1"))
        self.Game.setTabText(self.Game.indexOf(self.GamePage), _translate("MainWindow", "Tab 2"))
        self.Game.setTabText(self.Game.indexOf(self.Statistics), _translate("MainWindow", "Page"))
        self.menu.setTitle(_translate("MainWindow", "Login"))
        self.menuGame.setTitle(_translate("MainWindow", "Game"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())